_CODELISTS: dict[str, dict[str, str]] = {
    "notification_type": {
        "01": "Early notification",
        "02": "Advance notification",
        "03": "Notification confirmed",
        "04": "Update (block)",
        "05": "Delete notification",
    },
    "product_form": {
        "BB": "Hardback",
        "BC": "Paperback",
        "EA": "Digital download and online",
        "ED": "E-book reader",
        "DG": "Digital (various formats)",
    },
    "publishing_status": {
        "01": "Cancelled",
        "02": "Forthcoming",
        "03": "Postponed indefinitely",
        "04": "Active",
        "05": "No longer our product",
        "06": "Out of stock indefinitely",
        "07": "Out of print",
        "08": "Inactive",
        "09": "Unknown",
        "10": "Remaindered",
        "11": "Withdrawn from sale",
        "12": "Recalled",
    },
    "availability": {
        "10": "Not yet available",
        "20": "Available",
        "21": "In stock",
        "22": "To order",
        "23": "Pod",
        "30": "Temporarily unavailable",
        "40": "Not available",
        "41": "Not available, replaced by new product",
        "42": "Not available, other format available",
        "43": "No longer supplied",
        "44": "Apply direct",
        "45": "Not sold separately",
        "46": "Withdrawn",
        "47": "Remaindered",
        "48": "Out of stock indefinitely",
        "99": "Apply direct",
    },
    "contributor_role": {
        "A01": "By (author)",
        "A02": "With",
        "A03": "Screenplay by",
        "A04": "Libretto by",
        "A06": "Translated by",
        "A07": "As told to",
        "A08": "Film introduction by",
        "A09": "Introduction by",
        "A10": "Foreword by",
        "A11": "Preface by",
        "A12": "Edited by",
        "A13": "Edited and translated by",
        "A14": "Series edited by",
        "A15": "Edited with commentary by",
        "A19": "Index by",
        "A21": "Illustrated by",
        "A23": "Photographs by",
        "A24": "Preface by",
        "A29": "Maps by",
        "A30": "Conceived by",
        "A31": "Designed by",
        "A32": "Cover design or artwork by",
        "A36": "Music by",
        "A38": "Original author",
        "A39": "Maps by",
        "B01": "Edited by",
        "B06": "Volume editor",
        "B09": "Compiled by",
        "B10": "Selected by",
        "C01": "General editor",
        "D01": "Producer",
        "D02": "Director",
        "E07": "Read by",
        "E08": "Performed by",
    },
    "price_type": {
        "01": "RRP excluding tax",
        "02": "RRP including tax",
        "03": "Fixed retail price excluding tax",
        "04": "Fixed retail price including tax",
        "05": "Supplier's net price excluding tax",
        "06": "Supplier's net price including tax",
        "07": "Supplier's net price excluding tax: rental goods",
        "08": "Supplier's net price including tax: rental goods",
    },
    "subject_scheme": {
        "01": "Proprietary",
        "02": "ISBN subject category",
        "03": "Warengruppen-Systematik",
        "04": "Subjects for children's books",
        "05": "BIC subject category",
        "06": "BISAC subject heading",
        "07": "Library of Congress subject heading",
        "08": "Other subject scheme",
        "09": "DDC",
        "10": "BISAC",
        "11": "LC classification",
        "12": "UDC",
        "13": "Regensburger Verbundklassifikation",
        "14": "YBP (YPG)",
        "20": "Keywords",
        "23": "BIC subject qualifier",
        "24": "BISAC geographic qualifier",
        "93": "Thema subject code",
        "94": "Thema geographic qualifier",
        "95": "Thema language qualifier",
        "96": "Thema time period qualifier",
        "97": "Thema educational purpose qualifier",
        "98": "Thema interest age / special interest qualifier",
        "99": "Thema style qualifier",
    },
}


def code_to_label(code_type: str, code: str) -> str:
    """Returns human-readable label for a codelist entry, or the code itself if unknown."""
    return _CODELISTS.get(code_type, {}).get(code, code)
