"""ONIX short tag → reference name mapping.

Complete 510-entry mapping generated from the official ONIX 3.1 XSD files
(ONIX_BookProduct_3.1_reference.xsd vs ONIX_BookProduct_3.1_short.xsd) by
pairing element definitions at matching line numbers.

ONIX 2.1 shares most element codes with ONIX 3.x; compound elements use
lowercase reference names (no codes). Call normalize_tag() to convert any
short tag local name to its reference name before element matching.
"""

from lxml import etree

_SHORT_TO_REF: dict[str, str] = {
    # --- A ---
    "x544": "AVDuration",
    "avitem": "AVItem",
    "x541": "AVItemIDType",
    "avitemidentifier": "AVItemIdentifier",
    "x540": "AVItemType",
    "addressee": "Addressee",
    "m380": "AddresseeIDType",
    "addresseeidentifier": "AddresseeIdentifier",
    "x300": "AddresseeName",
    "b046": "Affiliation",
    "x580": "AffiliationIDType",
    "affiliationidentifier": "AffiliationIdentifier",
    "j400": "AgentIDType",
    "agentidentifier": "AgentIdentifier",
    "j401": "AgentName",
    "j402": "AgentRole",
    "alternativename": "AlternativeName",
    "ancillarycontent": "AncillaryContent",
    "x424": "AncillaryContentDescription",
    "x423": "AncillaryContentType",
    "audience": "Audience",
    "b204": "AudienceCodeType",
    "b205": "AudienceCodeTypeName",
    "b206": "AudienceCodeValue",
    "b207": "AudienceDescription",
    "x578": "AudienceHeadingText",
    "audiencerange": "AudienceRange",
    "b075": "AudienceRangePrecision",
    "b074": "AudienceRangeQualifier",
    "b076": "AudienceRangeValue",
    "x584": "AwardingBody",
    # --- B ---
    "barcode": "Barcode",
    "x312": "BarcodeType",
    "batchbonus": "BatchBonus",
    "j264": "BatchQuantity",
    "bible": "Bible",
    "b352": "BibleContents",
    "b354": "BiblePurpose",
    "b356": "BibleReferenceLocation",
    "b357": "BibleTextFeature",
    "b355": "BibleTextOrganization",
    "b353": "BibleVersion",
    "b044": "BiographicalNote",
    "bodymanifest": "BodyManifest",
    "bodyresource": "BodyResource",
    "k169": "BookClubAdoption",
    # --- C ---
    "j375": "CBO",
    "x434": "CitationNote",
    "citedcontent": "CitedContent",
    "x430": "CitedContentType",
    "b209": "CityOfPublication",
    "collateraldetail": "CollateralDetail",
    "collection": "Collection",
    "x586": "CollectionElementLevel",
    "x582": "CollectionFrequency",
    "x344": "CollectionIDType",
    "collectionidentifier": "CollectionIdentifier",
    "collectionsequence": "CollectionSequence",
    "x481": "CollectionSequenceNumber",
    "x479": "CollectionSequenceType",
    "x480": "CollectionSequenceTypeName",
    "x329": "CollectionType",
    "comparisonproductprice": "ComparisonProductPrice",
    "complexity": "Complexity",
    "b078": "ComplexityCode",
    "b077": "ComplexitySchemeIdentifier",
    "b289": "ComponentNumber",
    "b288": "ComponentTypeName",
    "x299": "ContactName",
    "x427": "ContentAudience",
    "contentdate": "ContentDate",
    "x429": "ContentDateRole",
    "contentdetail": "ContentDetail",
    "contentitem": "ContentItem",
    "contributor": "Contributor",
    "contributordate": "ContributorDate",
    "x417": "ContributorDateRole",
    "b048": "ContributorDescription",
    "contributorplace": "ContributorPlace",
    "x418": "ContributorPlaceRelator",
    "contributorreference": "ContributorReference",
    "b035": "ContributorRole",
    "b049": "ContributorStatement",
    "k168": "CopiesSold",
    "copyrightowner": "CopyrightOwner",
    "b392": "CopyrightOwnerIDType",
    "copyrightowneridentifier": "CopyrightOwnerIdentifier",
    "copyrightstatement": "CopyrightStatement",
    "x588": "CopyrightStatementText",
    "x512": "CopyrightType",
    "b087": "CopyrightYear",
    "b047": "CorporateName",
    "x443": "CorporateNameInverted",
    "x451": "CountriesExcluded",
    "x449": "CountriesIncluded",
    "b251": "CountryCode",
    "x316": "CountryOfManufacture",
    "b083": "CountryOfPublication",
    "covermanifest": "CoverManifest",
    "coverresource": "CoverResource",
    "j152": "CurrencyCode",
    # --- D ---
    "b306": "Date",
    "m186": "DefaultCurrencyCode",
    "m184": "DefaultLanguageOfText",
    "x310": "DefaultPriceType",
    "a199": "DeletionText",
    "descriptivedetail": "DescriptiveDetail",
    "discount": "Discount",
    "x469": "DiscountAmount",
    "j364": "DiscountCode",
    "j363": "DiscountCodeType",
    "j378": "DiscountCodeTypeName",
    "discountcoded": "DiscountCoded",
    "j267": "DiscountPercent",
    "x467": "DiscountType",
    # --- E ---
    "b057": "EditionNumber",
    "b058": "EditionStatement",
    "x419": "EditionType",
    "b217": "EditionVersionNumber",
    "j272": "EmailAddress",
    "b325": "EndDate",
    "x543": "EndTime",
    "epublicensedate": "EpubLicenseDate",
    "x585": "EpubLicenseDateRole",
    "epublicenseexpression": "EpubLicenseExpression",
    "x510": "EpubLicenseExpressionLink",
    "x508": "EpubLicenseExpressionType",
    "x509": "EpubLicenseExpressionTypeName",
    "x511": "EpubLicenseName",
    "x317": "EpubTechnicalProtection",
    "epubusageconstraint": "EpubUsageConstraint",
    "epubusagelimit": "EpubUsageLimit",
    "x319": "EpubUsageStatus",
    "x318": "EpubUsageType",
    "x321": "EpubUsageUnit",
    "event": "Event",
    "x517": "EventAcronym",
    "x520": "EventDate",
    "x550": "EventDescription",
    "x547": "EventIDType",
    "eventidentifier": "EventIdentifier",
    "x516": "EventName",
    "x518": "EventNumber",
    "eventoccurrence": "EventOccurrence",
    "x521": "EventPlace",
    "x515": "EventRole",
    "eventsponsor": "EventSponsor",
    "x522": "EventSponsorIDType",
    "eventsponsoridentifier": "EventSponsorIdentifier",
    "x549": "EventStatus",
    "x519": "EventTheme",
    "x548": "EventType",
    "j302": "ExpectedDate",
    "extent": "Extent",
    "b218": "ExtentType",
    "b220": "ExtentUnit",
    "b219": "ExtentValue",
    "x421": "ExtentValueRoman",
    # --- F ---
    "j271": "FaxNumber",
    "x440": "FeatureNote",
    "x439": "FeatureValue",
    "b286": "FirstPageNumber",
    "j265": "FreeQuantity",
    "x412": "FromLanguage",
    "funding": "Funding",
    "x523": "FundingIDType",
    "fundingidentifier": "FundingIdentifier",
    # --- H ---
    "header": "Header",
    # --- I ---
    "b233": "IDTypeName",
    "b244": "IDValue",
    "x422": "Illustrated",
    "b062": "IllustrationsNote",
    "imprint": "Imprint",
    "x445": "ImprintIDType",
    "imprintidentifier": "ImprintIdentifier",
    "b079": "ImprintName",
    "x593": "ImprintNameInverted",
    "k167": "InitialPrintRun",
    "insertmanifest": "InsertManifest",
    "insertpoint": "InsertPoint",
    "x574": "InsertPointType",
    "x575": "InsertPointValue",
    "insertresource": "InsertResource",
    # --- K ---
    "b040": "KeyNames",
    # --- L ---
    "language": "Language",
    "b252": "LanguageCode",
    "b253": "LanguageRole",
    "b287": "LastPageNumber",
    "x446": "LatestReprintNumber",
    "b042": "LettersAfterNames",
    "b284": "LevelSequenceNumber",
    "x432": "ListName",
    "j377": "LocationIDType",
    "locationidentifier": "LocationIdentifier",
    "j349": "LocationName",
    # --- M ---
    "x583": "MainAudience",
    "x425": "MainSubject",
    "b063": "MapScale",
    "market": "Market",
    "marketdate": "MarketDate",
    "j408": "MarketDateRole",
    "marketpublishingdetail": "MarketPublishingDetail",
    "j407": "MarketPublishingStatus",
    "x406": "MarketPublishingStatusNote",
    "x587": "MarketReference",
    "measure": "Measure",
    "x315": "MeasureType",
    "c095": "MeasureUnitCode",
    "c094": "Measurement",
    "m183": "MessageNote",
    "m180": "MessageNumber",
    "m181": "MessageRepeat",
    "j263": "MinimumOrderQuantity",
    # --- N ---
    "nameassubject": "NameAsSubject",
    "x415": "NameIDType",
    "nameidentifier": "NameIdentifier",
    "x414": "NameType",
    "b041": "NamesAfterKey",
    "b039": "NamesBeforeKey",
    "newsupplier": "NewSupplier",
    "x411": "NoCollection",
    "n339": "NoContributor",
    "n386": "NoEdition",
    "x501": "NoPrefix",
    "x507": "NoProduct",
    "x577": "NoResource",
    "x579": "NoSupplement",
    "a002": "NotificationType",
    "b257": "Number",
    "x323": "NumberOfCopies",
    "b125": "NumberOfIllustrations",
    "x322": "NumberOfItemsOfThisForm",
    "b061": "NumberOfPages",
    # --- O ---
    "ONIXmessage": "ONIXMessage",
    "occurrencedate": "OccurrenceDate",
    "x554": "OccurrenceDateRole",
    "j350": "OnHand",
    "j351": "OnOrder",
    "onorderdetail": "OnOrderDetail",
    "x532": "OrderQuantityMinimum",
    "x533": "OrderQuantityMultiple",
    "j144": "OrderTime",
    # --- P ---
    "j145": "PackQuantity",
    "pagerun": "PageRun",
    "x545": "PalletQuantity",
    "x410": "PartNumber",
    "b337": "Percent",
    "b036": "PersonName",
    "b037": "PersonNameInverted",
    "x433": "PositionOnList",
    "x313": "PositionOnProduct",
    "x590": "PostalCode",
    "b247": "PrefixToKey",
    "price": "Price",
    "j151": "PriceAmount",
    "x468": "PriceCode",
    "x465": "PriceCodeType",
    "x477": "PriceCodeTypeName",
    "pricecoded": "PriceCoded",
    "pricecondition": "PriceCondition",
    "priceconditionquantity": "PriceConditionQuantity",
    "x464": "PriceConditionQuantityType",
    "x463": "PriceConditionType",
    "priceconstraint": "PriceConstraint",
    "priceconstraintlimit": "PriceConstraintLimit",
    "x530": "PriceConstraintStatus",
    "x529": "PriceConstraintType",
    "x531": "PriceConstraintUnit",
    "pricedate": "PriceDate",
    "x476": "PriceDateRole",
    "x506": "PriceIDType",
    "priceidentifier": "PriceIdentifier",
    "x535": "PricePartDescription",
    "j239": "PricePer",
    "j261": "PriceQualifier",
    "j266": "PriceStatus",
    "x462": "PriceType",
    "j262": "PriceTypeDescription",
    "x416": "PrimaryContentType",
    "x457": "PrimaryPart",
    "x301": "PrintedOnProduct",
    "prize": "Prize",
    "g129": "PrizeCode",
    "g128": "PrizeCountry",
    "x589": "PrizeIDType",
    "prizeidentifier": "PrizeIdentifier",
    "g343": "PrizeJury",
    "g126": "PrizeName",
    "x556": "PrizeRegion",
    "x503": "PrizeStatement",
    "g127": "PrizeYear",
    "product": "Product",
    "j396": "ProductAvailability",
    "productclassification": "ProductClassification",
    "b275": "ProductClassificationCode",
    "b274": "ProductClassificationType",
    "x555": "ProductClassificationTypeName",
    "x314": "ProductComposition",
    "productcontact": "ProductContact",
    "x483": "ProductContactIDType",
    "productcontactidentifier": "ProductContactIdentifier",
    "x484": "ProductContactName",
    "x482": "ProductContactRole",
    "b385": "ProductContentType",
    "b012": "ProductForm",
    "b014": "ProductFormDescription",
    "b333": "ProductFormDetail",
    "productformfeature": "ProductFormFeature",
    "b336": "ProductFormFeatureDescription",
    "b334": "ProductFormFeatureType",
    "b335": "ProductFormFeatureValue",
    "b221": "ProductIDType",
    "productidentifier": "ProductIdentifier",
    "b225": "ProductPackaging",
    "productpart": "ProductPart",
    "x455": "ProductRelationCode",
    "productsupply": "ProductSupply",
    "productiondetail": "ProductionDetail",
    "productionmanifest": "ProductionManifest",
    "professionalaffiliation": "ProfessionalAffiliation",
    "b045": "ProfessionalPosition",
    "k165": "PromotionCampaign",
    "promotiondetail": "PromotionDetail",
    "promotionalevent": "PromotionalEvent",
    "x502": "Proximity",
    "publisher": "Publisher",
    "x447": "PublisherIDType",
    "publisheridentifier": "PublisherIdentifier",
    "b081": "PublisherName",
    "x592": "PublisherNameInverted",
    "publisherrepresentative": "PublisherRepresentative",
    "publishingdate": "PublishingDate",
    "x448": "PublishingDateRole",
    "publishingdetail": "PublishingDetail",
    "b291": "PublishingRole",
    "b394": "PublishingStatus",
    "b395": "PublishingStatusNote",
    # --- Q ---
    "x320": "Quantity",
    "x466": "QuantityUnit",
    # --- R ---
    "x456": "ROWSalesRightsType",
    "x505": "Rate",
    "x525": "Rating",
    "x526": "RatingLimit",
    "x527": "RatingUnits",
    "a001": "RecordReference",
    "x311": "RecordSourceIDType",
    "recordsourceidentifier": "RecordSourceIdentifier",
    "a197": "RecordSourceName",
    "a194": "RecordSourceType",
    "b398": "RegionCode",
    "x452": "RegionsExcluded",
    "x450": "RegionsIncluded",
    "relatedmaterial": "RelatedMaterial",
    "relatedproduct": "RelatedProduct",
    "relatedwork": "RelatedWork",
    "religioustext": "ReligiousText",
    "religioustextfeature": "ReligiousTextFeature",
    "b359": "ReligiousTextFeatureCode",
    "b360": "ReligiousTextFeatureDescription",
    "b358": "ReligiousTextFeatureType",
    "b376": "ReligiousTextIdentifier",
    "k309": "ReprintDetail",
    "x536": "Reserved",
    "x436": "ResourceContentType",
    "resourcefeature": "ResourceFeature",
    "x438": "ResourceFeatureType",
    "x576": "ResourceFileContentDescription",
    "resourcefiledate": "ResourceFileDate",
    "x573": "ResourceFileDateRole",
    "x571": "ResourceFileDescription",
    "x567": "ResourceFileDetail",
    "resourcefilefeature": "ResourceFileFeature",
    "x570": "ResourceFileFeatureDescription",
    "x568": "ResourceFileFeatureType",
    "x569": "ResourceFileFeatureValue",
    "x572": "ResourceFileLink",
    "x441": "ResourceForm",
    "x565": "ResourceIDType",
    "resourceidentifier": "ResourceIdentifier",
    "x435": "ResourceLink",
    "x437": "ResourceMode",
    "x566": "ResourceRole",
    "resourceversion": "ResourceVersion",
    "resourceversionfeature": "ResourceVersionFeature",
    "x442": "ResourceVersionFeatureType",
    "j269": "ReturnsCode",
    "j268": "ReturnsCodeType",
    "x460": "ReturnsCodeTypeName",
    "returnsconditions": "ReturnsConditions",
    "x528": "ReturnsNote",
    "reviewrating": "ReviewRating",
    # --- S ---
    "salesoutlet": "SalesOutlet",
    "b393": "SalesOutletIDType",
    "salesoutletidentifier": "SalesOutletIdentifier",
    "b382": "SalesOutletName",
    "salesrestriction": "SalesRestriction",
    "x453": "SalesRestrictionNote",
    "b381": "SalesRestrictionType",
    "salesrights": "SalesRights",
    "b089": "SalesRightsType",
    "x420": "ScriptCode",
    "sender": "Sender",
    "m379": "SenderIDType",
    "senderidentifier": "SenderIdentifier",
    "x298": "SenderName",
    "x307": "SentDateTime",
    "b034": "SequenceNumber",
    "x330": "SourceName",
    "x428": "SourceTitle",
    "x431": "SourceType",
    "specificationbundlename": "SpecificationBundleName",
    "x558": "SpecificationBundleNameTypeName",
    "x559": "SpecificationBundleNameValue",
    "x564": "SpecificationDescription",
    "x560": "SpecificationDetail",
    "specificationfeature": "SpecificationFeature",
    "x563": "SpecificationFeatureDescription",
    "x561": "SpecificationFeatureType",
    "x562": "SpecificationFeatureValue",
    "b324": "StartDate",
    "x542": "StartTime",
    "stock": "Stock",
    "j297": "StockQuantityCode",
    "j293": "StockQuantityCodeType",
    "j296": "StockQuantityCodeTypeName",
    "stockquantitycoded": "StockQuantityCoded",
    "x552": "StreetAddress",
    "b389": "StudyBibleType",
    "subject": "Subject",
    "b069": "SubjectCode",
    "subjectdate": "SubjectDate",
    "x534": "SubjectDateRole",
    "x591": "SubjectDescription",
    "b070": "SubjectHeadingText",
    "b067": "SubjectSchemeIdentifier",
    "b171": "SubjectSchemeName",
    "b068": "SubjectSchemeVersion",
    "b029": "Subtitle",
    "b248": "SuffixToKey",
    "supplementmanifest": "SupplementManifest",
    "supplier": "Supplier",
    "x458": "SupplierCodeType",
    "x513": "SupplierCodeTypeName",
    "x459": "SupplierCodeValue",
    "j345": "SupplierIDType",
    "supplieridentifier": "SupplierIdentifier",
    "j137": "SupplierName",
    "supplierowncoding": "SupplierOwnCoding",
    "j292": "SupplierRole",
    "supplycontact": "SupplyContact",
    "x538": "SupplyContactIDType",
    "supplycontactidentifier": "SupplyContactIdentifier",
    "x539": "SupplyContactName",
    "x537": "SupplyContactRole",
    "supplydate": "SupplyDate",
    "x461": "SupplyDateRole",
    "supplydetail": "SupplyDetail",
    "supportingresource": "SupportingResource",
    # --- T ---
    "tax": "Tax",
    "x474": "TaxAmount",
    "x546": "TaxExempt",
    "x471": "TaxRateCode",
    "x472": "TaxRatePercent",
    "x470": "TaxType",
    "x473": "TaxableAmount",
    "j270": "TelephoneNumber",
    "territory": "Territory",
    "d104": "Text",
    "d107": "TextAuthor",
    "textcontent": "TextContent",
    "textitem": "TextItem",
    "b285": "TextItemIDType",
    "textitemidentifier": "TextItemIdentifier",
    "b290": "TextItemType",
    "textsource": "TextSource",
    "b374": "TextSourceCorporate",
    "x557": "TextSourceDescription",
    "x581": "TextSourceLink",
    "x426": "TextType",
    "b369": "ThesisPresentedTo",
    "b368": "ThesisType",
    "b370": "ThesisYear",
    "timerun": "TimeRun",
    "titledetail": "TitleDetail",
    "titleelement": "TitleElement",
    "x409": "TitleElementLevel",
    "b030": "TitlePrefix",
    "x478": "TitleStatement",
    "b203": "TitleText",
    "b202": "TitleType",
    "b031": "TitleWithoutPrefix",
    "b043": "TitlesAfterNames",
    "b038": "TitlesBeforeNames",
    "x413": "ToLanguage",
    "x514": "ToQuantity",
    "b384": "TradeCategory",
    # --- U ---
    "b249": "UnnamedPersons",
    "j192": "UnpricedItemType",
    # --- V ---
    "velocity": "Velocity",
    "x504": "VelocityMetric",
    "x551": "VenueName",
    "x553": "VenueNote",
    # --- W ---
    "website": "Website",
    "b294": "WebsiteDescription",
    "b295": "WebsiteLink",
    "b367": "WebsiteRole",
    "b201": "WorkIDType",
    "workidentifier": "WorkIdentifier",
    "x454": "WorkRelationCode",
    # --- Y ---
    "b020": "YearOfAnnual",
    # ONIX 2.1 specific elements not in 3.1 XSD
    "title": "Title",
    "series": "Series",
    "personnameidentifier": "PersonNameIdentifier",
    "b250": "PersonNameIDType",
    "mediafile": "MediaFile",
    "f114": "MediaFileTypeCode",
    "f116": "MediaFileLink",
    "j148": "PriceTypeCode",
}


def normalize_tag(local_name: str) -> str:
    """Converts an ONIX short tag local name to its reference name.
    Unknown tags are returned unchanged (already reference names or unrecognised)."""
    return _SHORT_TO_REF.get(local_name, local_name)


def normalize_elem_tree(elem: etree._Element) -> None:
    """Renames all short tag element names in an lxml element tree to reference names.
    Operates in-place; safe to call on both short tag and reference tag files."""
    for e in elem.iter():
        if not isinstance(e.tag, str):
            continue
        if e.tag and e.tag[0] == "{":
            ns, local = e.tag[1:].split("}", 1)
            normalized = normalize_tag(local)
            if normalized != local:
                e.tag = f"{{{ns}}}{normalized}"
        else:
            normalized = normalize_tag(e.tag)
            if normalized != e.tag:
                e.tag = normalized
